version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: OnlineExamWeb/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
